export const KENJI = {
  name:     'Kenji Mendoza',
  first:    'Kenji',
  last:     'Mendoza',
  role:     'Technical Support Engineer & iOS Developer',
  company:  'Zerohash',
  location: 'Manila, Philippines',
  tz:       'Asia/Manila',
  email:    'codewithkendev@gmail.com',
  github:   'https://github.com/CodeWithDevKen',
  linkedin: 'https://www.linkedin.com/in/kenji-mendoza-094b792a4/',
  tagline:  'Software Developer — Manila ✦ Craft over speed',
  bio:      'I solve problems for a living — first in technical support, now through code. Currently keeping fintech running at Zerohash while building my first iOS app and transitioning into full-time software development. I believe the best developers come from understanding real user problems first.',
  now: {
    building:  'CourtbookPH — court booking, end to end',
    cup:       'Single-origin pour-over, Benguet',
    sound:     'Bill Evans — vinyl, side B',
    reading:   'The Pragmatic Programmer (again)',
    tinkering: 'React Native + SwiftUI mobile patterns',
  },
  projects: [
    {
      id:      'courtbook',
      name:    'CourtbookPH',
      year:    '2026',
      status:  'In progress',
      kind:    'Full-stack web app',
      one:     'A court-booking platform for the Philippines — find a court, reserve a slot, pay, done.',
      detail:  'Real-time availability, role-based access for venue owners and players, and a checkout flow that respects local payment habits. Designed to scale from one barangay court to a national network.',
      stack:   ['Next.js', 'Supabase', 'NextAuth', 'Prisma', 'Tailwind', 'PostgreSQL'],
      slot:    'CourtbookPH — booking flow',
      metrics: [['Surface', 'Web + responsive'], ['Role', 'Design + build'], ['Status', 'Building in public']] as [string, string][],
    },
    {
      id:      'portfolio',
      name:    'This Portfolio',
      year:    '2026',
      status:  'Live',
      kind:    'Personal site',
      one:     'The site you are looking at — a portfolio that behaves like a workshop, not a résumé.',
      detail:  'Hand-built, dark, and a little classic. Live status, interactive work cards, and a skills view that is more dashboard than checklist.',
      stack:   ['Next.js', 'React', 'TypeScript', 'Tailwind', 'Vercel'],
      slot:    'Portfolio — hero & work',
      metrics: [['Surface', 'Web'], ['Role', 'Design + build'], ['Status', 'Shipped']] as [string, string][],
    },
  ],
  skills: [
    { group: 'Frontend',  items: [['React / Next.js', 90], ['TypeScript', 85], ['Tailwind CSS', 88], ['UI / Interaction', 80]] as [string, number][] },
    { group: 'Backend',   items: [['Node.js', 82], ['PostgreSQL', 78], ['Prisma ORM', 80], ['Supabase', 84]] as [string, number][] },
    { group: 'Mobile',    items: [['React Native', 78], ['Swift / SwiftUI', 60], ['Firebase SDK', 75], ['SwiftData', 58]] as [string, number][] },
    { group: 'Craft',     items: [['Debugging', 92], ['Fintech support', 88], ['Documentation', 84], ['Code review', 80]] as [string, number][] },
  ],
  career: [
    {
      role:    'Technical Support Engineer',
      company: 'Zerohash',
      period:  'Nov 2025 — Present',
      where:   'Remote · Manila',
      blurb:   'Front-line engineering support for crypto & fintech infrastructure — debugging API integrations, tracing settlement issues, and turning recurring tickets into documentation and tooling.',
      tags:    ['APIs', 'Fintech', 'Debugging', 'SQL'],
      current: true,
    },
    {
      role:    'Jr. Technical Support Engineer',
      company: 'Zerohash',
      period:  'Feb 2025 — Nov 2025',
      where:   'Remote · Manila',
      blurb:   'Handled complex technical issues and debugged API integrations daily, bridging the gap between technical teams and end users.',
      tags:    ['APIs', 'Fintech', 'Customer Success'],
      current: false,
    },
    {
      role:    'Jr. Software Developer',
      company: 'Avior Marine Inc',
      period:  'Jan 2024 — Jan 2025',
      where:   'Manila',
      blurb:   'Designed and shipped web apps end-to-end — from wireframe to deploy. Built internal tooling with .NET and React.',
      tags:    ['React', 'ASP.NET MVC', 'C#', 'SQL Server'],
      current: false,
    },
    {
      role:    'Jr. Technical Support',
      company: 'Asterisko Artisan',
      period:  'Apr 2023 — Mar 2024',
      where:   'Manila',
      blurb:   'Cut my teeth on real customer issues, learned how to read a codebase I didn\'t write, and discovered that the best developers are the most patient ones.',
      tags:    ['Technical Support', 'Troubleshooting'],
      current: false,
    },
  ],
  certs: [
    ['FIX Protocol Training', 'Fixnox', 'Dec 2025'],
    ['Claude 101',            'Anthropic', 'May 2026'],
    ['Claude Code 101',       'Anthropic', 'May 2026'],
  ] as [string, string, string][],
  links: [
    ['GitHub',   'github.com/CodeWithDevKen'],
    ['LinkedIn', 'in/kenji-mendoza-094b792a4'],
    ['Email',    'codewithkendev@gmail.com'],
  ] as [string, string][],
};

export const GAUGES: [string, number][] = [
  ['React / Next.js', 90],
  ['TypeScript',       85],
  ['Supabase',         84],
  ['Node.js',          82],
  ['Prisma',           80],
  ['Debugging',        92],
];
